server:
  port: 8082

spring:
  application:
    name: push-notifications-listener

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/notifications-db?authSource=admin


